apiVersion: v2
name: "envoy-gateway-tls-controller"
description: Envoy gateway tls controller chart template
type: application
version: 1.0.0
appVersion: "0.1.0"

maintainers:
  - email: wizardy.oni@gmail.com
    name: Ivan Chizh
    url: https://github.com/drone117

dependencies:
  - name: commonlib
    repository: oci://nix-docker.registry.twcstorage.ru/helm/libs
    version: 1.0.0