---

image:
  # -- image registry
  registry: nix-docker.registry.twcstorage.ru
  # -- image repository
  repository: 
  # -- image tag
  tag: 
  # -- image digest
  digest: 
  # -- image pull policy
  pullPolicy: Always

serviceAccount:
  # -- service account name
  name: kopf-envoy-account
  # -- service account auto mount token
  automountServiceAccountToken: true

rbac:
  # -- cluster role name
  clusterRoleName: kopf-envoy-cluster
  # -- cluster role binding name
  clusterRoleBindingName: kopf-envoy-cluster-rolebinding
  # -- namespaced role name
  namespacedRoleName: kopf-envoy-namespaced
  # -- namesapced role binding name
  namespacedRoleBindingName: kopf-envoy-namespaced-rolebinding

# -- replica count
replicaCount: 1
# -- progress deadline seconds
progressDeadlineSeconds: 180
# -- revision history limit
revisionHistoryLimit: 1

updateStrategy:
  # -- update strategy type
  type: RollingUpdate
  rollingUpdate:
    # -- strategy max surge
    maxSurge: 1
    # -- strategy max unavailable
    maxUnavailable: 1

service:
  # -- service port (app)
  port: 3000

resources:
  requests:
    # -- cpu requests
    cpu: 250m
    # -- memory requests
    memory: 256Mi
  limits:
    # -- cpu limits
    cpu: 500m
    # memory limits
    memory: 768Mi

probes:
  liveness:
    # -- liveness probe host
    host: &livenessHost localhost
    # -- liveness probe path
    path: &healthEndpoint /healthz
    # -- liveness probe initial delay
    initialDelaySeconds: 60
    # -- liveness probe period
    periodSeconds: 5
    # -- liveness probe timeout per attempt
    timeoutSeconds: 1
    # -- liveness probe max consecutive failures before restart
    failureThreshold: 5
  readiness:
    # -- readiness probe host
    host: *livenessHost
    # -- readiness probe path
    path: *healthEndpoint
    # -- readiness probe inital delay
    initialDelaySeconds: 60
    # -- readiness probe period
    periodSeconds: 5
    # -- readiness probe timeout per attempt
    timeoutSeconds: 1
    # -- readiness probe max consecutive failures before unready
    failureThreshold: 5

app:
  # -- app arguments
  args:
    # -- set the home folder for app
    homeFolder: &homeFolder /app
    # -- specify the script location that defines which operator to run
    scriptLocation: /src/certificate/certificate.py
  # -- app configmap
  conf:
    envoy:
      # -- api parameters for envoy
      apiGroup: gateway.networking.k8s.io
      apiVersion: v1
      apiPlural: gateways
      # -- envoy gateway name to patch
      envoyGatewayName: "envoy-gateway"
    certificate:
      # -- api parameters for certificate
      apiGroup: cert-manager.io
      apiVersion: v1
      apiPlural: certificates
    # -- config path
    configPath: &configPath config
    # -- config name
    configName: &configName config
    # -- if set to False the app will try to get kube api by in cluster config
    externalKubernetesConfig: False
    # -- what suffix to add to certificate name ex. {name}-{suffix}
    nameSuffix: "envoy-gateway-tls"
    # -- defines the string value to use in order to check whether the certificate is created
    readinessString: "Certificate is up to date and has not expired"
  env:
    APP_CONFIG_DIR: *configPath
    APP_CONFIG_NAME: *configName
    HOME: *homeFolder