apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.rbac.namespacedRoleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.namespacedRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}